// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: grpc-stream/proto/order.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderStream_StreamOrders_FullMethodName = "/grpcstream.OrderStream/StreamOrders"
)

// OrderStreamClient is the client API for OrderStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderStreamClient interface {
	StreamOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Order, StreamResponse], error)
}

type orderStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderStreamClient(cc grpc.ClientConnInterface) OrderStreamClient {
	return &orderStreamClient{cc}
}

func (c *orderStreamClient) StreamOrders(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Order, StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OrderStream_ServiceDesc.Streams[0], OrderStream_StreamOrders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Order, StreamResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderStream_StreamOrdersClient = grpc.BidiStreamingClient[Order, StreamResponse]

// OrderStreamServer is the server API for OrderStream service.
// All implementations must embed UnimplementedOrderStreamServer
// for forward compatibility.
type OrderStreamServer interface {
	StreamOrders(grpc.BidiStreamingServer[Order, StreamResponse]) error
	mustEmbedUnimplementedOrderStreamServer()
}

// UnimplementedOrderStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderStreamServer struct{}

func (UnimplementedOrderStreamServer) StreamOrders(grpc.BidiStreamingServer[Order, StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamOrders not implemented")
}
func (UnimplementedOrderStreamServer) mustEmbedUnimplementedOrderStreamServer() {}
func (UnimplementedOrderStreamServer) testEmbeddedByValue()                     {}

// UnsafeOrderStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderStreamServer will
// result in compilation errors.
type UnsafeOrderStreamServer interface {
	mustEmbedUnimplementedOrderStreamServer()
}

func RegisterOrderStreamServer(s grpc.ServiceRegistrar, srv OrderStreamServer) {
	// If the following call panics, it indicates UnimplementedOrderStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderStream_ServiceDesc, srv)
}

func _OrderStream_StreamOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(OrderStreamServer).StreamOrders(&grpc.GenericServerStream[Order, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OrderStream_StreamOrdersServer = grpc.BidiStreamingServer[Order, StreamResponse]

// OrderStream_ServiceDesc is the grpc.ServiceDesc for OrderStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcstream.OrderStream",
	HandlerType: (*OrderStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamOrders",
			Handler:       _OrderStream_StreamOrders_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "grpc-stream/proto/order.proto",
}
